const MSG_EVENT_CONSTANT = {
  KICK_OFF: 'KICK_OFF',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  RECEIVE_MSG: 'RECEIVE_MSG',
  RECEIVE_MSG_ERROR: 'RECEIVE_MSG_ERROR',
  SEND_MSG_SUCCESS: 'SEND_MSG_SUCCESS',
  SEND_MSG_ERROR: 'SEND_MSG_ERROR',
  GET_OFFLINE_MSG: 'GET_OFFLINE_MSG',
  GET_OFFLINE_MSG_ERROR: 'GET_OFFLINE_MSG_ERROR',
  HEAT_ERROR: 'HEAT_ERROR',
  NETWORK_CLOSE: 'NETWORK_CLOSE',
  NETWORK_RECONNECT: 'NETWORK_RECONNECT'
}


export {
  MSG_EVENT_CONSTANT
}
